In [1]:
import numpy as np
import toydiff as tdf
import matplotlib.pyplot as plt

In [2]:
from toydiff.nn.functional import tanh

In [3]:
a = tdf.random.rand((5,5), track_gradient=True)
b = tdf.random.rand((5,1), track_gradient=True)

In [4]:
c = a + b

try:
    c.backward()
except Exception as e:
    print(e)

In [5]:
c.gradient.numpy()

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)

In [6]:
a.numpy()

array([[0.29945374, 0.5802881 , 0.14942324, 0.31747103, 0.9549782 ],
       [0.7747026 , 0.7351697 , 0.92151785, 0.5071975 , 0.16026714],
       [0.6302548 , 0.5140062 , 0.03852043, 0.7737813 , 0.52010405],
       [0.2176063 , 0.5797469 , 0.9308685 , 0.7201687 , 0.00861837],
       [0.56100965, 0.22167163, 0.27094242, 0.21113035, 0.9072038 ]],
      dtype=float32)

In [7]:
b.numpy()

array([[0.93478215],
       [0.44630638],
       [0.36340377],
       [0.7405627 ],
       [0.7675519 ]], dtype=float32)

In [8]:
----

SyntaxError: invalid syntax (2133496677.py, line 1)

In [ ]:
fig, ax = plt.subplots(1,1)

x = tdf.Tensor(np.linspace(-7, 7, 200), track_gradient=True)

# f(x)
y = tanh(x)
ax.plot(x.numpy(), y.numpy(), label="Tanh(x)")

# first order
y.backward()
ax.plot(x.numpy(), x.gradient.numpy(), label="First order")
x.zero_grad()

# second order
y = 1 - tanh(x) ** 2
y.backward()
ax.plot(x.numpy(), x.gradient.numpy(), label="Second order")
x.zero_grad()

ax.legend()
ax.grid(True, alpha=.5)

----

In [ ]:
import torch
import toydiff as tdf

In [ ]:
arr = np.random.rand(5, 5)
tensor_a = tdf.Tensor(arr, track_gradient=True)
tensor_b = tdf.Tensor(arr * 5, track_gradient=True)
tensor_c = tdf.Tensor(arr[:, [1]], track_gradient=True)

t_tensor_a = torch.Tensor(arr.copy())
t_tensor_a.requires_grad = True
t_tensor_b = torch.Tensor(arr.copy() * 5)
t_tensor_b.requires_grad = True
t_tensor_c = torch.Tensor(arr[:, [1]])
t_tensor_c.requires_grad = True

out_t = torch.matmul(t_tensor_a, t_tensor_b) + t_tensor_c
out = tdf.matmul(tensor_a, tensor_b) + tensor_c
out_t = torch.matmul(t_tensor_a, t_tensor_b) + t_tensor_c

In [ ]:
out_t.backward(torch.ones_like(out_t))
out.backward()

In [ ]:
out

In [ ]:
out.parents[0]

In [ ]:
out.parents[1]

In [ ]:
out.gradient.numpy().sum(axis=1)

In [ ]:
t_tensor_c.grad

In [ ]:
out.parents[0].size

In [ ]:
out.parents[1].size

In [ ]:
np.testing.assert_allclose(out.numpy(), out_t.detach().numpy(), rtol=RTOL)

# check backward
np.testing.assert_allclose(tensor_a.gradient.numpy(), t_tensor_a.grad.numpy(), rtol=RTOL)
np.testing.assert_allclose(tensor_b.gradient.numpy(), t_tensor_b.grad.numpy(), rtol=RTOL)
np.testing.assert_allclose(tensor_c.gradient.numpy(), t_tensor_c.grad.numpy(), rtol=RTOL)