In [1]:
import torch
import numpy as np
import toydiff as tdf

In [2]:
a = tdf.rand((3,3), track_gradient=True)

In [3]:
_a = np.ones((3,3)) * 2
_a[0, 2] = 23
_a[2, 2] = 9

_b = np.ones(3) * 6


ta = torch.Tensor(_a)
ta.requires_grad = True

tb = torch.Tensor(_b)
tb.requires_grad = True

tc = torch.divide(ta, tb)
tc.backward(torch.ones_like(tc))

# --------------------------------
a = tdf.Tensor(_a, track_gradient=True)
b = tdf.Tensor(_b, track_gradient=True)

c = a / b
c.backward()

In [4]:
a.gradient

Tensor([[0.16666667, 0.16666667, 0.16666667],
       [0.16666667, 0.16666667, 0.16666667],
       [0.16666667, 0.16666667, 0.16666667]], dtype=float32, track_gradient=False)

In [5]:
ta.grad.numpy()

array([[0.16666667, 0.16666667, 0.16666667],
       [0.16666667, 0.16666667, 0.16666667],
       [0.16666667, 0.16666667, 0.16666667]], dtype=float32)

In [6]:
b.gradient

Tensor([-0.16666667, -0.16666667, -0.9444445 ], dtype=float32, track_gradient=False)

In [7]:
tb.grad.numpy()

array([-0.16666667, -0.16666667, -0.9444445 ], dtype=float32)

In [8]:
from toydiff.core import OperationRunner

In [9]:
ta.detach().numpy()

array([[ 2.,  2., 23.],
       [ 2.,  2.,  2.],
       [ 2.,  2.,  9.]], dtype=float32)

In [26]:
def generate_input(shape, n_tensors=1):
    def create(shape):
        arr = np.random.rand(*shape)
        tensor = tdf.Tensor(arr, track_gradient=True)
        torch_tensor = torch.Tensor(arr)
        torch_tensor.requires_grad = True
        return tensor, torch_tensor

    tensors = []
    for _ in (0, n_tensors):
        tensors.append(create(shape))
    return tensors

In [32]:
(a, b), (c, d) = generate_input((2,2), 2)

In [33]:
a

Tensor([[0.37627852, 0.7490264 ],
       [0.03910809, 0.34865263]], dtype=float32, track_gradient=True)

In [46]:
np.matmul(np.random.rand(3,2,3), np.random.rand(3,3,3))

array([[[0.39478895, 1.15658499, 0.82277207],
        [0.63980949, 1.76936085, 1.13080599]],

       [[0.64147438, 0.65505143, 0.78471273],
        [0.74230255, 0.70379491, 0.54446901]],

       [[0.08331157, 0.90414339, 0.86060323],
        [0.10623665, 0.94678403, 0.94784125]]])

In [47]:
(t1, t1_torch), (t2, t2_torch) = generate_input((3,))
out = tdf.minimum(t1, t2)
out_torch = torch.minimum(t1_torch, t2_torch)

In [52]:
np.minimum(t1.numpy(), t2.numpy())

array([0.13808706, 0.33257085, 0.41192052], dtype=float32)

In [50]:
t1

Tensor([0.8621172 , 0.77184314, 0.41192052], dtype=float32, track_gradient=True)

In [51]:
t2

Tensor([0.13808706, 0.33257085, 0.708585  ], dtype=float32, track_gradient=True)

In [48]:
out

Tensor([0.8621172 , 0.77184314, 0.708585  ], dtype=float32, backward_fn=<Minimum(BinaryOp).Backward>)

In [49]:
out_torch

tensor([0.1381, 0.3326, 0.4119], grad_fn=<MinimumBackward0>)